apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-paradox
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/FatmaBn/argocd-15-min.git
    targetRevision: HEAD
    path: helm
    helm:
      values: | 
        image:
          tag: latest
      version: v3
  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: production

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
